services:
  db:
    image: mariadb:latest
    container_name: mariadb
    env_file:
      - .env.db
    restart: always
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./db/initfile.sql:/docker-entrypoint-initdb.d/initfile.sql
    networks:
      - wildlens_db
    healthcheck:
      test: [ "CMD", "mariadb-admin", "ping", "-h", "127.0.0.1" ]
      interval: 25s
      retries: 10
      start_period: 30s

  wildlens_backend:
    image: wildlens-backend:latest
    container_name: wildlens_backend
    env_file:
      - .env.backend
    ports:
      - "8001:8001"
    depends_on:
      db:
        condition: service_healthy
      wildlens_prediction:
        condition: service_started
    networks:
      - wildlens_backend
      - wildlens_db

  wildlens_prediction:
    image: wildlens-prediction:latest
    container_name: wildlens_prediction
    env_file:
      - .env.prediction
    ports:
      - "8002:8002"
    networks:
      - wildlens_backend
#   If you want cannot use GPU, comment the following lines
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - "9090:9090"
    restart: unless-stopped
    volumes:
      - ./prometheus:/etc/prometheus
      - prom_data:/prometheus
    networks:
      - wildlens_backend
      - wildlens_visualization

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    restart: unless-stopped
    env_file:
      - .env.grafana
    volumes:
      - ./grafana:/etc/grafana/provisioning/datasources
      - grafana_data:/var/lib/grafana

    networks:
      - wildlens_visualization


networks:
  wildlens_backend:
    driver: bridge
  wildlens_db:
    driver: bridge
  wildlens_visualization:
    driver: bridge

volumes:
  mariadb_data:
    driver: local

  prom_data:
    driver: local

  grafana_data:
    driver: local