services:
  db:
    image: mariadb:latest
    container_name: mariadb
    env_file:
      - .env.db
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    restart: always
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./initfile.sql:/docker-entrypoint-initdb.d/initfile.sql
    networks:
      - wildlens_network
    healthcheck:
      test: [ "CMD", "mariadb-admin", "ping", "-h", "127.0.0.1" ]
      interval: 10s
      retries: 10
      start_period: 30s

  wildlens_backend:
    image: wildlens-backend:latest
    container_name: wildlens_backend
    env_file:
      - .env
    ports:
      - "8001:8001"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - wildlens_network

networks:
  wildlens_network:
    driver: bridge

volumes:
  mariadb_data:
    driver: local