FROM jenkins/inbound-agent:jdk17 AS base

USER root

# Installation des dépendances nécessaires
RUN apt-get update && apt-get install -y \
    build-essential \
    libssl-dev \
    zlib1g-dev \
    libbz2-dev \
    libreadline-dev \
    libsqlite3-dev \
    wget \
    curl \
    llvm \
    libncurses5-dev \
    libncursesw5-dev \
    xz-utils \
    tk-dev \
    libffi-dev \
    liblzma-dev \
    software-properties-common \
    ca-certificates \
    git

# Téléchargement et installation de Python 3.12
WORKDIR /tmp
RUN wget https://www.python.org/ftp/python/3.12.0/Python-3.12.0.tgz \
    && tar -xvf Python-3.12.0.tgz \
    && cd Python-3.12.0 \
    && ./configure --enable-optimizations \
    && make -j$(nproc) \
    && make altinstall

# Création des liens symboliques pour python3 et pip3,
RUN ln -sf /usr/local/bin/python3.12 /usr/local/bin/python3 \
    && ln -sf /usr/local/bin/pip3.12 /usr/local/bin/pip3

# Installation de pip et mise à jour
RUN python3 -m ensurepip \
    && python3 -m pip install --upgrade pip

# Installation des packages Python couramment utilisés,
RUN pip3 install pytest pytest-cov pylint flake8

# Vérification de l'installation
RUN python3 --version && pip3 --version

# Revenir à l'utilisateur jenkins
USER jenkins

# Sleep pour garder le conteneur actif
CMD ["sleep", "infinity"]