global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'wildlens-backend'
    static_configs:
      - targets: ['wildlens_backend:8002']

  - job_name: 'wildlens-prediction'
    static_configs:
      - targets: ['wildlens_prediction:5002']
